import { User, RideRequest } from './types';

export const USERS: Record<string, User> = {
  om: {
    id: 'om',
    name: 'Om Choubey',
    email: 'om@lawazia.com',
    role: 'student',
  },
  rahul: {
    id: 'rahul',
    name: 'Rahul Kumar',
    email: 'rahul@lawazia.com',
    role: 'employee',
  },
  raj: {
    id: 'raj',
    name: 'Raj Kumar',
    email: 'raj@lawazia.com',
    role: 'rider',
  },
};

export const INITIAL_RIDE_REQUESTS: RideRequest[] = [
  {
    id: 'TOTO-1024',
    from: 'college',
    to: 'station',
    date: '2026-10-03',
    time: '10:30 AM',
    passengers: [
      { id: 'p1', name: 'Om Choubey', status: 'PENDING' },
      { id: 'p2', name: 'Rahul Kumar', status: 'PENDING' },
      { id: 'p3', name: 'Amit Kumar', status: 'PENDING' },
    ],
    requestedBy: 'om',
    requestedByName: 'Om Choubey',
    status: 'REQUESTED',
    createdAt: '10:22 AM',
  },
  {
    id: 'TOTO-1025',
    from: 'office',
    to: 'college',
    date: '2026-10-03',
    time: '10:30 AM',
    passengers: [
      { id: 'p4', name: 'Priya Sharma', status: 'PENDING' },
      { id: 'p5', name: 'Neha Singh', status: 'PENDING' },
    ],
    requestedBy: 'rahul',
    requestedByName: 'Rahul Kumar',
    status: 'REQUESTED',
    createdAt: '10:25 AM',
  },
  {
    id: 'TOTO-1026',
    from: 'station',
    to: 'office',
    date: '2026-10-03',
    time: '12:30 PM',
    passengers: [
      { id: 'p6', name: 'Amit Kumar', status: 'PENDING' },
    ],
    requestedBy: 'rahul',
    requestedByName: 'Amit Kumar',
    status: 'REQUESTED',
    createdAt: '10:28 AM',
  },
];

// Past completed trips for history
export const PAST_TRIPS: RideRequest[] = [
  {
    id: 'TOTO-1020',
    from: 'station',
    to: 'college',
    date: '2026-10-01',
    time: '09:00 AM',
    passengers: [
      { id: 'h1', name: 'Om Choubey', status: 'BOARDED' },
      { id: 'h2', name: 'Rahul Kumar', status: 'BOARDED' },
    ],
    requestedBy: 'om',
    requestedByName: 'Om Choubey',
    status: 'COMPLETED',
    createdAt: '08:50 AM',
    acceptedAt: '08:52 AM',
    startedAt: '08:58 AM',
    completedAt: '09:15 AM',
  },
  {
    id: 'TOTO-1018',
    from: 'college',
    to: 'office',
    date: '2026-09-30',
    time: '02:00 PM',
    passengers: [
      { id: 'h3', name: 'Om Choubey', status: 'MISSED' },
      { id: 'h4', name: 'Priya Sharma', status: 'BOARDED' },
    ],
    requestedBy: 'rahul',
    requestedByName: 'Priya Sharma',
    status: 'COMPLETED',
    createdAt: '01:45 PM',
    acceptedAt: '01:47 PM',
    startedAt: '01:55 PM',
    completedAt: '02:20 PM',
  },
  {
    id: 'TOTO-1015',
    from: 'office',
    to: 'station',
    date: '2026-09-29',
    time: '05:30 PM',
    passengers: [
      { id: 'h5', name: 'Om Choubey', status: 'BOARDED' },
    ],
    requestedBy: 'om',
    requestedByName: 'Om Choubey',
    status: 'COMPLETED',
    createdAt: '05:20 PM',
    acceptedAt: '05:22 PM',
    startedAt: '05:28 PM',
    completedAt: '05:45 PM',
  },
  {
    id: 'TOTO-1012',
    from: 'station',
    to: 'college',
    date: '2026-09-28',
    time: '08:30 AM',
    passengers: [
      { id: 'h6', name: 'Rahul Kumar', status: 'BOARDED' },
      { id: 'h7', name: 'Neha Singh', status: 'BOARDED' },
      { id: 'h8', name: 'Amit Kumar', status: 'BOARDED' },
    ],
    requestedBy: 'rahul',
    requestedByName: 'Rahul Kumar',
    status: 'COMPLETED',
    createdAt: '08:15 AM',
    acceptedAt: '08:18 AM',
    startedAt: '08:25 AM',
    completedAt: '08:50 AM',
  },
  {
    id: 'TOTO-1010',
    from: 'college',
    to: 'station',
    date: '2026-09-27',
    time: '04:00 PM',
    passengers: [
      { id: 'h9', name: 'Om Choubey', status: 'BOARDED' },
      { id: 'h10', name: 'Rahul Kumar', status: 'MISSED' },
    ],
    requestedBy: 'om',
    requestedByName: 'Om Choubey',
    status: 'COMPLETED',
    createdAt: '03:45 PM',
    acceptedAt: '03:48 PM',
    startedAt: '03:55 PM',
    completedAt: '04:20 PM',
  },
];
